questions = [
        {'question': 'Would you rather go into the past and meet your ancestors or go into the future and meet your great-great grandchildren?', 'id': 1},
{'question': 'Would you rather have more time or more money?', 'id': 2},
{'question': 'Would you rather have a rewind button or a pause button on your life?', 'id': 3},
{'question': 'Would you rather be able to talk with the animals or speak all foreign languages?', 'id': 4},
{'question': 'Would you rather win the lottery or live twice as long?', 'id': 5},
{'question': 'Would you feel worse if no one showed up to your wedding or to your funeral?', 'id': 6},
{'question': 'Would you rather be without internet for a week, or without your phone?', 'id': 7},
{'question': 'Would you rather meet George Washington, or the current President?', 'id': 8},
{'question': 'Would you rather lose your vision or your hearing?', 'id': 9},
{'question': 'Would you rather work more hours per day, but fewer days or work fewer hours per day, but more days?', 'id': 10},
{'question': 'Would you rather listen to music from the 70’s or music from today?', 'id': 11},
{'question': 'Would you rather become someone else or just stay you?', 'id': 12},
{'question': 'Would you rather be Batman or Spiderman?', 'id': 13},
{'question': 'Would you rather be stuck on a broken ski lift or in a broken elevator?', 'id': 14},
{'question': 'For your birthday, would you rather receive cash or gifts?', 'id': 15},
{'question': 'Would you rather go to a movie or to dinner alone?', 'id': 16},
{'question': 'Would you rather always say everything on your mind or never speak again?', 'id': 17},
{'question': 'Would you rather make a phone call or send a text?', 'id': 18},
{'question': 'Would you rather read an awesome book or watch a good movie?', 'id': 19},
{'question': 'Would you rather be the most popular person at work or school or the smartest?', 'id': 20},
{'question': 'Would you rather put a stop to war or end world hunger?', 'id': 21},
{'question': 'Would you rather spend the night in a luxury hotel room or camping surrounded by beautiful scenery?', 'id': 22},
{'question': 'Would you rather explore space or the ocean?', 'id': 23},
{'question': 'Would you rather go deep sea diving or bungee jumping?', 'id': 24},
{'question': 'Would you rather be a kid your whole life or an adult your whole life?', 'id': 25},
{'question': 'Would you rather go on a cruise with friends or with your spouse?', 'id': 26},
{'question': 'Would you rather lose your keys or your cell phone?', 'id': 27},
{'question': 'Would you rather eat a meal of cow tongue or octopus?', 'id': 28},
{'question': 'Would you rather have x-ray vision or magnified hearing?', 'id': 29},
{'question': 'Would you rather work in a group or work alone?', 'id': 30},
{'question': 'Would you rather be stuck on an island alone or with someone who talks incessantly?', 'id': 31},
{'question': 'Would you rather be too hot or too cold?', 'id': 32},
{'question': 'When you’re old, would you rather die before or after your spouse?', 'id': 33},
{'question': 'Would you rather have a cook or a maid?', 'id': 34},
{'question': 'Would you rather be the youngest or the oldest sibling?', 'id': 35},
{'question': 'Would you rather get rich through hard work or through winning the lottery?', 'id': 36},
{'question': 'Would you rather have a 10-hour dinner with a headstrong politician from an opposing party, or attend a 10-hour concert for a music group you detest?', 'id': 37},
{'question': 'Would you rather be an Olympic gold medalist or a Nobel Peace Prize winner?', 'id': 38},
{'question': 'Would you rather have a desk job or an outdoor job?', 'id': 39},
{'question': 'Would you rather live at the top of a tall NYC apartment building or at the top of a mountain?', 'id': 40},
{'question': 'Would you rather have Rambo or The Terminator on your side?', 'id': 41},
{'question': 'Would you rather be proposed to in private or in front of family and friends?', 'id': 42},
{'question': 'Would you rather have to sew all your clothes or grow your own food?', 'id': 43},
{'question': 'Would you rather hear the good news or the bad news first?', 'id': 44},
{'question': 'Would you rather be your own boss or work for someone else?', 'id': 45},
{'question': 'Would you rather have nosy neighbors or noisy neighbors?', 'id': 46},
{'question': 'Would you rather be on a survival reality show or dating game show?', 'id': 47},
{'question': 'Would you rather be too busy or be bored?', 'id': 48},
{'question': 'Would you rather watch the big game at home or live at the stadium.', 'id': 49},
{'question': 'Would you rather be too busy or be bored?', 'id': 50},
{'question': 'Would you rather watch the big game at home or live at the stadium.', 'id': 51},
{'question': 'Would you rather spend the day with your favorite athlete or you favorite movie star?', 'id': 52},
{'question': 'Would you rather live where it is constantly winter or where it is constantly summer?', 'id': 53},
{'question': 'Would you rather travel the US and see the sights in a motorhome or by plane?', 'id': 54},
{'question': 'Would you rather be a little late or way too early?', 'id': 55},
{'question': 'Would you rather have an unlimited gift certificate to a restaurant or a clothing store?', 'id': 56},
{'question': 'Would you rather date someone you met online or go on a blind date?', 'id': 57},
{'question': 'Would you rather your kids wear a uniform to school or clothing of their choice?', 'id': 58},
{'question': 'Would you rather have many good friends or one very best friend?', 'id': 59},
{'question': 'Would you rather live in Antarctica or the Sahara Dessert?', 'id': 60},
{'question': 'Would you rather be able to take back anything you say or hear every conversation around you?', 'id': 61},
{'question': 'Would you rather be 4’5” or 7’7”?', 'id': 62},
{'question': 'Would you rather be poor and work at a job you love, or rich and work at a job you hate?', 'id': 63},
{'question': 'Would you rather have your flight delayed by 8 hours or lose your luggage?', 'id': 64},
{'question': 'Would you rather be in your pajamas or a suit all day?', 'id': 65},
{'question': 'Would you rather have your first child when you are 18 or 40?', 'id': 66},
{'question': 'Would you rather be the star player on a losing basketball team or ride the bench on a winning one?', 'id': 67},
{'question': 'Would you rather spend the next year exempt from all taxes or have a one-month paid vacation?', 'id': 68},
{'question': 'Would you rather have the best house in a bad neighborhood or the worst house in a good neighborhood?', 'id': 69},
{'question': 'Would you rather be filthy rich and live 400 years ago or be poor but live today?', 'id': 70},
{'question': 'Would you rather be gossiped about or never talked about at all?', 'id': 71},
{'question': 'Would you rather end hunger or hatred?', 'id': 72},
{'question': 'Would you rather be an unknown major league baseball player or a famous badminton star?', 'id': 73},
{'question': 'Would you rather go without TV or junk food the rest of your life?', 'id': 74},
{'question': 'Would you rather spend the day at an amusement park or lazing on the beach?', 'id': 75},
{'question': 'Would you rather be fluent in all languages or be a master of every musical instrument?', 'id': 76},
{'question': 'Would you rather sing a song in front of complete strangers or your closest friends?', 'id': 77},
{'question': 'Would you rather own your own boat or your own plane?', 'id': 78},
{'question': 'Would you rather meet the president of the United States or a movie star?', 'id': 79},
{'question': 'Would you rather spend two weeks stuck in a psychiatric hospital or stuck in an airport?', 'id': 80},
{'question': 'If you had to give up one thing for the rest of your life, would it be brushing your hair or brushing your teeth?', 'id': 81},
{'question': 'Would you rather spend 20 years in prison and be exonerated as innocent or be put away for four years (despite your innocence) and be considered guilty forever?', 'id': 82},
{'question': 'Would you rather own a house or rent a residence?', 'id': 83},
{'question': 'Would you rather be known as a one-hit wonder for a novel or a song?', 'id': 84},
{'question': 'Would you rather take an action-packed European vacation or spend two weeks at the same Caribbean resort?', 'id': 85},
{'question': 'Would you rather be a character in an action-packed thriller or a romantic comedy?', 'id': 86},
{'question': 'Would you rather be stuck on a train or a bus?', 'id': 87},
{'question': 'Would you rather be a part of an arranged marriage or spend your life as a single person?', 'id': 88},
{'question': 'Would you rather babysit a crying infant for a day or have an unwanted houseguest for a week?', 'id': 89},
{'question': 'Would you rather be locked in an amusement park or a library?', 'id': 90},
{'question': 'Would you rather sing like an opera star or cook like a gourmet chef?', 'id': 91},
{'question': 'Would you rather have your debt forgiven or have guaranteed good health for a decade?', 'id': 92},
{'question': 'Would you rather live the rest of your life as a monk or followed continuously by paparazzi?', 'id': 93},
{'question': 'Would you rather be given a lifetime supply of delicious food or books?', 'id': 94},
{'question': 'Would you rather be able to breath underwater or fly through the air?', 'id': 95},
{'question': 'Would you rather be known for your intelligence or your good looks?', 'id': 96},
{'question': 'Would you rather eat pizza or ice cream as the only food for eternity?', 'id': 97},
{'question': 'Would you rather mentally or physically never age?', 'id': 98},
{'question': 'Would you rather change your eye color or your hair color?', 'id': 99},
{'question': 'Would you rather have the details of your financial life or your love life be made public?', 'id': 100},
{'question': 'Would you rather spend a year as a cop or a teacher in an inner-city neighborhood?', 'id': 101},
{'question': 'Would you rather have a family of 12 children or never be able to have children at all?', 'id': 102},
{'question': 'Would you rather the aliens that make first contact be robotic or organic?', 'id': 103},
{'question': 'Would you rather lose the ability to read or lose the ability to speak?', 'id': 104},
{'question': 'Would you rather have a golden voice or a silver tongue?', 'id': 105},
{'question': 'Would you rather be covered in fur or covered in scales?', 'id': 106},
{'question': 'Would you rather be in jail for a year or lose a year off your life?', 'id': 107},
{'question': 'Would you rather always be 10 minutes late or always be 20 minutes early?', 'id': 108},
{'question': 'Would you rather have one real get out of jail free card or a key that opens any door?', 'id': 109},
{'question': 'Would you rather know the history of every object you touched or be able to talk to animals?', 'id': 110},
{'question': 'Would you rather be married to a 10 with a bad personality or a 6 with an amazing personality?', 'id': 111},
{'question': 'Would you rather be able to talk to land animals, animals that fly, or animals that live under the water?', 'id': 112},
{'question': 'Would you rather have all traffic lights you approach be green or never have to stand in line again?', 'id': 113},
{'question': 'Would you rather spend the rest of your life with a sailboat as your home or an RV as your home?', 'id': 114},
{'question': 'Would you rather give up all drinks except for water or give up eating anything that was cooked in an oven?', 'id': 115},
{'question': 'Would you rather be able to see 10 minutes into your own future or 10 minutes into the future of anyone but yourself?', 'id': 116},
{'question': 'Would you rather have an easy job working for someone else or work for yourself but work incredibly hard?', 'id': 117},
{'question': 'Would you rather be the first person to explore a planet or be the inventor of a drug that cures a deadly disease?', 'id': 118},
{'question': 'Would you rather go back to age 5 with everything you know now or know now everything your future self will learn?', 'id': 119},
{'question': 'Would you rather be able to control animals (but not humans) with your mind or control electronics with your mind?', 'id': 120},
{'question': 'Would you rather have unlimited international first-class tickets or never have to pay for food at restaurants?', 'id': 121},
{'question': 'Would you rather see what was behind every closed door or be able to guess the combination of every safe on the first try?', 'id': 122},
{'question': 'Would you rather be an average person in the present or a king of a large country 2500 years ago?', 'id': 123},
{'question': 'Would you rather be able to dodge anything no matter how fast it’s moving or be able to ask any three questions and have them answered accurately?', 'id': 124},
{'question': 'Would you rather be forced to dance every time you heard music or be forced to sing along to any song you heard?', 'id': 125},
{'question': 'Would you rather have all your clothes fit perfectly or have the most comfortable pillow, blankets, and sheets in existence?', 'id': 126},
{'question': 'Would you rather 5% of the population have telepathy, or 5% of the population have telekinesis? You are not part of the 5% that has telepathy or telekinesis', 'id': 127},
{'question': 'Would you rather be an unimportant character in the last movie you saw or an unimportant character in the last book you read?', 'id': 128},
{'question': 'Would you rather move to a new city or town every week or never be able to leave the city or town you were born in?', 'id': 129},
{'question': 'Would you rather be completely insane and know that you are insane or completely insane and believe you are sane?', 'id': 130},
{'question': 'Would you rather travel the world for a year on a shoestring budget or stay in only one country for a year but live in luxury?', 'id': 131},
{'question': 'Would you rather suddenly be elected a senator or suddenly become a CEO of a major company? (You won’t have any more knowledge about how to do either job than you do right now', 'id': 132},
{'question': 'Would you rather live in virtual reality where you are all powerful or live in the real world and be able to go anywhere but not be able to interact with anyone or anything?', 'id': 133},
{'question': 'Would you rather have whatever you are thinking to appear above your head for everyone to see or have absolutely everything you do live streamed for anyone to see?', 'id': 134},
{'question': 'Would you rather be only able to watch the few movies with a Rotten Tomatoes score of 95-100% or only be able to watch the majority of movies with a Rotten Tomatoes score of 94% and lower?', 'id': 135},
{'question': 'Would you rather wake up as a new random person every year and have full control of them for the whole year or once a week spend a day inside a stranger without having any control of them?', 'id': 136},
{'question': 'Would you rather know how above or below average you are at everything or know how above or below average people are at one skill/talent just by looking at them?', 'id': 137},
{'question': 'Would you rather live until you are 200 but look like you are 200 the whole time even though you are healthy or look like you are 25 all the way until you die at age 65?', 'id': 138},
{'question': 'Would you rather be a reverse centaur or a reverse mermaid/merman?', 'id': 139},
{'question': 'Would you rather your only mode of transportation be a donkey or a giraffe?', 'id': 140},
{'question': 'Would you rather only be to use a fork (no spoon) or only be able to use a spoon (no fork)?', 'id': 141},
{'question': 'Would you rather every shirt you ever wear be kind of itchy or only be able to use 1 ply toilet paper?', 'id': 142},
{'question': 'Would you rather have edible spaghetti hair that regrows every night or sweat (not sweet) maple syrup?', 'id': 143},
{'question': 'Would you rather have to read aloud every word you read or sing everything you say out loud?', 'id': 144},
{'question': 'Would you rather wear a wedding dress/tuxedo every single day or wear a bathing suit every single day?', 'id': 145},
{'question': 'Would you rather be unable to move your body every time it rains or not be able to stop moving while the sun is out?', 'id': 146},
{'question': 'Would you rather have all dogs try to attack you when they see you or all birds try to attack you when they see you?', 'id': 147},
{'question': 'Would you rather be compelled to high five everyone you meet or be compelled to give wedgies to anyone in a green shirt?', 'id': 148},
{'question': 'Would you rather have skin that changes color based on your emotions or tattoos appear all over your body depicting what you did yesterday?', 'id': 149},
{'question': 'Would you rather randomly time travel +/- 20 years every time you fart or teleport to a different place on earth (on land, not water) every time you sneeze?', 'id': 150},
{'question': 'Would you rather there be a perpetual water balloon war going on in your city/town or a perpetual food fight?', 'id': 151},
{'question': 'Would you rather have to fart loudly every time you have a serious conversation or have to burp after every kiss?', 'id': 152},
{'question': 'Would you rather become twice as strong when both of your fingers are stuck in your ears or crawl twice as fast as you can run?', 'id': 153},
{'question': 'Would you rather have everything you draw become real but be permanently terrible at drawing or be able to fly but only as fast as you can walk?', 'id': 154},
{'question': 'Would you rather thirty butterflies instantly appear from nowhere every time you sneeze or one very angry squirrel appear from nowhere every time you cough?', 'id': 155},
{'question': 'Would you rather vomit uncontrollably for one minute every time you hear the happy birthday song or get a headache that lasts for the rest of the day every time you see a bird (including in pictures or a video)?', 'id': 156},
{'question': 'Would you rather eat a sandwich made from 4 ingredients in your fridge chosen at random or eat a sandwich made by a group of your friends from 4 ingredients in your fridge?', 'id': 157},
{'question': 'Would you rather everyone be required to wear identical silver jumpsuits or any time two people meet and are wearing an identical article of clothing they must fight to the death?', 'id': 158},
{'question': 'Would you rather be a famous director or a famous actor?', 'id': 159},
{'question': 'Would you rather be a practicing doctor or a medical researcher?', 'id': 160},
{'question': 'Would you rather live in a cave or live in a tree house?', 'id': 161},
{'question': 'Would you rather be able to control fire or water?', 'id': 162},
{'question': 'Would you rather live without the internet or live without AC and heating?', 'id': 163},
{'question': 'Would you rather be able to teleport anywhere or be able to read minds?', 'id': 164},
{'question': 'Would you rather be unable to use search engines or unable to use social media?', 'id': 165},
{'question': 'Would you rather be beautiful/handsome but stupid or intelligent but ugly?', 'id': 166},
{'question': 'Would you rather be balding but fit or overweight with a full head of hair?', 'id': 167},
{'question': 'Would you rather never be able to eat meat or never be able to eat vegetables?', 'id': 168},
{'question': 'Would you rather have a completely automated home or a self-driving car?', 'id': 169},
{'question': 'Would you rather be an amazing painter or a brilliant mathematician?', 'id': 170},
{'question': 'Would you rather be famous but ridiculed or be just a normal person?', 'id': 171},
{'question': 'Would you rather have a flying carpet or a car that can drive underwater?', 'id': 172},
{'question': 'Would you rather never be stuck in traffic again or never get another cold?', 'id': 173},
{'question': 'Would you rather have a bottomless box of Legos or a bottomless gas tank?', 'id': 174},
{'question': 'Would you rather be forced to eat only spicy food or only incredibly bland food?', 'id': 175},
{'question': 'Would you rather be a bowling champion or a curling champion?', 'id': 176},
{'question': 'Would you rather be fantastic at riding horses or amazing at driving dirt bikes?', 'id': 177},
{'question': 'Would you rather never be able to wear pants or never be able to wear shorts?', 'id': 178},
{'question': 'Would you rather live the next 10 years of your life in China or Russia?', 'id': 179},
{'question': 'Would you rather live on the beach or in a cabin in the woods?', 'id': 180},
{'question': 'Would you rather be lost in a bad part of town or lost in the forest?', 'id': 181},
{'question': 'Would you rather have a horrible short-term memory or a horrible long-term memory?', 'id': 182},
{'question': 'Would you rather be completely invisible for one day or be able to fly for one day?', 'id': 183},
{'question': 'Would you rather never be able to use a touchscreen or never be able to use a keyboard and mouse?', 'id': 184},
{'question': 'Would you rather have unlimited sushi for life or unlimited tacos for life? (both are amazingly delicious and can be any type of sushi/taco you want)', 'id': 185},
{'question': 'Would you rather get one free round trip international plane ticket every year or be able to fly domestic anytime for free?', 'id': 186},
{'question': 'Would you rather be able to be free from junk mail or free from email spam for the rest of your life?', 'id': 187},
{'question': 'Would you rather give up bathing for a month or give up the internet for a month?', 'id': 188},
{'question': 'Would you rather give up watching TV/movies for a year or give up playing games for a year?', 'id': 189},
{'question': 'Would you rather never be able to drink sodas like coke again or only be able to drink sodas and nothing else?', 'id': 190},
{'question': 'Would you rather have amazingly fast typing/texting speed or be able to read ridiculously fast?', 'id': 191},
{'question': 'Would you rather live under a sky with no stars at night or live under a sky with no clouds during the day?', 'id': 192},
{'question': 'Would you rather have free Wi-Fi wherever you go or be able to drink unlimited free coffee at any coffee shop?', 'id': 193},
{'question': 'Would you rather take amazing selfies, but all of your other pictures are horrible or take breathtaking photographs of anything but yourself?', 'id': 194},
{'question': 'Would you rather never get a paper cut again or never get something stuck in your teeth again?', 'id': 195},
{'question': 'Would you rather never have another embarrassing fall in public or never feel the need to pass gas in public again?', 'id': 196},
{'question': 'Would you rather lose your best friend or all of your friends except for your best friend?', 'id': 197},
{'question': 'Would you rather it never stops snowing (the snow never piles up) or never stops raining (the rain never causes floods)?', 'id': 198},
{'question': 'Would you rather never be able to leave your own country or never be able to fly in an airplane?', 'id': 199},
{'question': 'Would you rather never have a toilet clog on you again or never have the power go out again?', 'id': 200},
{'question': 'Would you rather earbuds and headphones never sit right on / in your ears or have all music either slightly too quiet or slightly too loud?', 'id': 201},
{'question': 'Would you rather be the best in the world at climbing trees or the best in the world at jumping rope?', 'id': 202},
{'question': 'Would you rather never run out of battery power for whatever phone and tablet you own or always have free Wi-Fi wherever you go?', 'id': 203},
{'question': 'Would you rather never have to clean a bathroom again or never have to do dishes again?', 'id': 204},
{'question': 'Would you rather eat an egg with a half-formed chicken inside or eat ten cooked grasshoppers?', 'id': 205},
{'question': 'Would you rather only wear one color each day or have to wear seven colors each day?', 'id': 206},
{'question': 'Would you rather eat rice with every meal and never be able to eat bread or eat bread with every meal and never be able to eat rice?', 'id': 207},
{'question': 'Would you rather travel the world for a year all expenses paid or have $40,000 to spend on whatever you want?', 'id': 208},
{'question': 'Would you rather be able to go to any theme park in the world for free for the rest of your life or eat for free at any drive-through restaurant for the rest of your life?', 'id': 209},
{'question': 'Would you rather be the absolute best at something that no one takes seriously or be well above average but not anywhere near the best at something well respected?', 'id': 210},
{'question': 'Would you rather it be impossible for you to be woken up for 11 straight hours every day, but you wake up feeling amazing, or you can be woken up normally but never feel totally rested?', 'id': 211},
{'question': 'Would you rather have everything in your house perfectly organized by a professional or have a professional event company throw the best party you’ve ever been to, in your honor?', 'id': 212},
{'question': 'Would you rather have unlimited amounts of any material you want to build a house, but you have to build the house all by yourself or have a famed architect design and build you a modest house?', 'id': 213},
{'question': 'Would you rather never sweat again but not be more prone to heat stroke or never feel cold again but cold still physically affects you (i', 'id': 214},
{'question': 'Would you rather super sensitive taste or super sensitive hearing?', 'id': 215},
{'question': 'Would you rather have constantly dry eyes or a constant runny nose?', 'id': 216},
{'question': 'Would you rather never lose your phone again or never lose your keys again?', 'id': 217},
{'question': 'Would you rather have out of control body hair or a strong, pungent body odor?', 'id': 218},
{'question': 'Would you rather be unable to have kids or only be able to conceive quintuplets?', 'id': 219},
{'question': 'Would you rather clean rest stop toilets or work in a slaughterhouse for a living?', 'id': 220},
{'question': 'Would you rather lose all your money and valuables or all the pictures you have ever taken?', 'id': 221},
{'question': 'Would you rather find your true love or a suitcase with five million dollars inside?', 'id': 222},
{'question': 'Would you rather not be able to see any colors or have mild but constant tinnitus (ringing in the ears)?', 'id': 223},
{'question': 'Would you rather have chapped lips that never heal or terrible dandruff that can’t be treated?', 'id': 224},
{'question': 'Would you rather live without hot water for showers/baths or live without a washing machine?', 'id': 225},
{'question': 'Would you rather be alone for the rest of your life or always be surrounded by annoying people?', 'id': 226},
{'question': 'Would you rather be locked in a room that is constantly dark for a week or a room that is constantly bright for a week?', 'id': 227},
{'question': 'Would you rather accidentally be responsible for the death of a child or accidentally be responsible for the deaths of three adults?', 'id': 228},
{'question': 'Would you rather know when you are going to die or how you are going to die? (You can’t change the time or method of your death', 'id': 229},
{'question': 'Would you rather have everything you eat be too salty or not salty enough no matter how much salt you add?', 'id': 230},
{'question': 'Would you rather never have to work again or never have to sleep again (you won’t feel tired or suffer negative health effects)?', 'id': 231},
{'question': 'Would you rather never use social media sites/apps again or never watch another movie or TV show?', 'id': 232},
{'question': 'Would you rather be fluent in all languages and never be able to travel or be able to travel anywhere for a year but never be able to learn a word of a different language?', 'id': 233},
{'question': 'Would you rather be put in a maximum-security federal prison with the hardest of the hardened criminals for one year or be put in a relatively relaxed prison where wall street types are held for ten years?', 'id': 234},
{'question': 'Would you rather have everything on your phone right now (browsing history, photos, etc', 'id': 235},
{'question': 'Would you rather be an amazing artist but not be able to see any of the art you created or be an amazing musician but not be able to hear any of the music you create?', 'id': 236},
{'question': 'Would you rather have everyone laugh at your jokes but not find anyone else’s jokes funny or have no one laugh at your jokes but you still find other people’s jokes funny?', 'id': 237},
{'question': 'Would you rather wake up in the middle of an unknown desert or wake up in a rowboat on an unknown body of water?', 'id': 238},
{'question': 'Would you rather always have a great body for your entire life but have slightly below average intelligence or have a mediocre body for your entire life but be slightly above average in intelligence?', 'id': 239},
{'question': 'Would you rather be in debt for $100,000 or never be able to make more than $3,500 a month?', 'id': 240},
{'question': 'Would you rather have the police hunting you for a murder you didn’t commit or a psychopathic clown hunting you?', 'id': 241},
{'question': 'Would you rather be constantly tired no matter how much you sleep or constantly hungry no matter how much you eat?', 'id': 242},
{'question': 'Would you rather live a comfortable and peaceful life in the woods in a small cabin without much human interaction or a life full of conflict and entertainment in a mansion in a city?', 'id': 243},
{'question': 'Would you rather walk around work or school for the whole day without realizing there is a giant brown stain on the back of your pants or realize the deadline for that important paper/project was yesterday, and you are nowhere near done?', 'id': 244},
{'question': 'Would you rather be so afraid of heights that you can’t go to the second floor of a building or be so afraid of the sun that you can only leave the house on rainy days?', 'id': 245},
{'question': 'Would you rather get tipsy from just one sip of alcohol and ridiculously drunk from just one alcoholic drink or never get drunk no matter how much alcohol you drank?', 'id': 246},
{'question': 'Would you rather be hired for a well-paying job that you lied to get and have no idea how to do or be about to give the most important presentation of your life but you can’t remember any of the material you prepared?', 'id': 247},
{'question': 'Would you rather be feared by all or loved by all?', 'id': 248},
{'question': 'Would you rather sell all of your possessions or sell one of your organs?', 'id': 249},
{'question': 'Would you rather be infamous in history books or be forgotten after your death?', 'id': 250},
{'question': 'Would you rather be reincarnated as a fly or just cease to exist after you die?', 'id': 251},
{'question': 'Would you rather never get angry or never be envious?', 'id': 252},
{'question': 'Would you rather have a horribly corrupt government or no government?', 'id': 253},
{'question': 'Would you rather be held in high regard by your parents or your friends?', 'id': 254},
{'question': 'Would you rather be poor but help people or become incredibly rich by hurting people?', 'id': 255},
{'question': 'Would you rather humans go to the moon again or go to mars?', 'id': 256},
{'question': 'Would you rather know the uncomfortable truth of the world or believe a comforting lie?', 'id': 257},
{'question': 'Would you rather die in 20 years with no regrets or die in 50 years with many regrets?', 'id': 258},
{'question': 'Would you rather be transported permanently 500 years into the future or 500 years into the past?', 'id': 259},
{'question': 'Would you rather donate your body to science or donate your organs to people who need them?', 'id': 260},
{'question': 'Would you rather be famous when you are alive and forgotten when you die or unknown when you are alive but famous after you die?', 'id': 261},
{'question': 'Would you rather go to jail for 4 years for something you didn’t do or get away with something horrible you did but always live in fear of being caught?', 'id': 262},
{'question': 'Would you rather live in the wilderness far from civilization with no human contact or live on the streets of a city as a homeless person?', 'id': 263},
{'question': 'Would you rather live your entire life in a virtual reality where all your wishes are granted or just in the normal real world?', 'id': 264},
{'question': 'Would you rather have a horrible job, but be able to retire comfortably in 10 years or have your dream job, but have to work until the day you die?', 'id': 265},
{'question': 'Would you rather lose all of your memories from birth to now or lose your ability to make new long-term memories?', 'id': 266},
{'question': 'Would you rather always be able to see 5 minutes into the future or always be able to see 100 years into the future?', 'id': 267},
{'question': 'Would you rather be forced to kill one innocent person or five people who committed minor crimes?', 'id': 268},
{'question': 'Would you rather work very hard at a rewarding job or hardly have to work at a job that isn’t rewarding?', 'id': 269},
{'question': 'Would you rather have a criminal justice system that actually works and is fair or an administrative branch that is free of corruption?', 'id': 270},
{'question': 'Would you rather have real political power but be relatively poor or be ridiculously rich and have no political power?', 'id': 271},
{'question': 'Would you rather have the power to gently nudge anyone’s decisions or have complete puppet master control of five people?', 'id': 272},
{'question': 'Would you rather live in a utopia as a normal person or in a dystopia but you are the supreme ruler?', 'id': 273},
{'question': 'Would you rather snitch on your best friend for a crime they committed or go to jail for the crime they committed?', 'id': 274},
{'question': 'Would you rather be born again in a totally different life or born again with all the knowledge you have now?', 'id': 275},
{'question': 'Would you rather all conspiracy theories be true or live in a world where no leaders really know what they are doing?', 'id': 276},
{'question': 'Would you rather know all the mysteries of the universe or know every outcome of every choice you make?', 'id': 277},
{'question': 'Would you rather spend two years with your soul mate only to have them die and you never love again or spend your life with someone nice you settled for?', 'id': 278},
{'question': 'Would you rather have all corporations know all of your computer usage or the government know all of your computer usage?', 'id': 279},
{'question': 'Would you rather inherit 20 million dollars when you turn 18 or spend the time earning 50 million dollars through your hard work?', 'id': 280},
{'question': 'Would you rather the general public think you are a horrible person, but your family is very proud of you, or your family thinks you are a horrible person, but the general public be very proud of you?', 'id': 281},
{'question': 'Would you rather fight for a cause you believe in, but doubt will succeed or fight for a cause that you only partially believe in but have a high chance of your cause succeeding?', 'id': 282},
{'question': 'Would you rather be famous for inventing a deadly new weapon or invent something that helps the world but someone else gets all the credit for inventing it?', 'id': 283},
{'question': 'Would you rather live in a haunted house where the ghosts ignore you and do their own thing or be a ghost in a house living out a pleasant and uneventful week from your life again and again?', 'id': 284},
{'question': 'Would you rather write a novel that will be widely considered the most important book in the past 200 years, but you and the book will only be appreciated after your death or be the most famous erotica writer of your generation?', 'id': 285},
{'question': 'Would you rather have done something horribly embarrassing and only your best friend knows or not done something horribly embarrassing, but everyone except your best friend thinks you did it?', 'id': 286},
{'question': 'Would you rather your shirts be always two sizes too big or one size too small?', 'id': 287},
{'question': 'Would you rather find five dollars on the ground or find all your missing socks?', 'id': 288},
{'question': 'Would you rather have one nipple or two belly buttons?', 'id': 289},
{'question': 'Would you rather eat a ketchup sandwich or a Siracha sandwich?', 'id': 290},
{'question': 'Would you rather use a push lawnmower with a bar that is far too high or far too low?', 'id': 291},
{'question': 'Would you rather eat a box of dry spaghetti noodles or two cups of uncooked rice?', 'id': 292},
{'question': 'Would you rather eat a spoonful of wasabi or a spoonful of extremely spicy hot sauce?', 'id': 293},
{'question': 'Would you rather have hands that kept growing as you got older or feet that kept growing as you got older?', 'id': 294},
{'question': 'Would you rather not be able to open any closed doors (locked or unlocked) or not be able to close any open doors?', 'id': 295},
{'question': 'Would you rather have plants grow at 20 times their normal rate when you are near or for people and animals to stop aging when you are near them?', 'id': 296},
{'question': 'Would you rather always feel like someone is following you, but no one is, or always feel like someone is watching you, even though no one is?', 'id': 297},
{'question': 'Would you rather live in a house with see-through walls in a city or in the same see-through house but in the middle of a forest far from civilization?', 'id': 298},
{'question': 'Would you rather have every cat or dog that gets lost end up at your house or everyone’s clothes that they forget in the dryer get teleported to your house?', 'id': 299},
{'question': 'Would you rather blink twice the normal rate or not be able to blink for 5 minutes but then have to close your eyes for 10 seconds every 5 minutes?', 'id': 300},
{'question': 'Would you rather all plants scream when you cut them / pick their fruit or animals beg for their lives before they are killed?', 'id': 301},
{'question': 'Would you rather wake up each morning to find that a random animal appendage has replaced your nondominant arm or permanently replace your bottom half with an animal bottom of your choice (not human)?', 'id': 302},
{'question': 'Would you rather have a map that shows you the location of anything you want to find and can be used again and again but has a margin of error of up to five miles or a device that allows you to find the location of anything you want with incredible accuracy but can only be used three times?', 'id': 303},
{'question': 'Would you rather have all animals feel compelled to obey you if you come within 10 feet of them or be given the opportunity to genetically design a pet that will be loyal only to you with the combined DNA of three animals?', 'id': 304},
{'question': 'Would you rather have someone impersonating you and doing really amazing things that you get the credit for or find money hidden in weird places all around your house every day but you can’t figure out where the money comes from or how it keeps getting there?', 'id': 305},
{'question': 'Would you rather wake up every morning with a new hundred-dollar bill in your pocket but not know where it came from or wake up every morning with a new fifty-dollar bill in your pocket and know where it comes from?', 'id': 306},
{'question': 'Would you rather have a clown only you can see that follows you everywhere and just stands silently in a corner watching you without doing or saying anything or have a real-life stalker who dresses like the Easter bunny that everyone can see?', 'id': 307},
{'question': 'Would you rather be an amazing virtuoso at any instrument but only if you play naked or be able to speak any language but only if you close your eyes and dance while you are doing it?', 'id': 308},
{'question': 'Would you rather everything you dream each night come true when you wake up or everything a randomly chosen person dreams each night come true when they wake up?', 'id': 309},
{'question': 'Would you rather have a boomerang that would find and kill any one person of your choosing, anywhere in the world, but can only be used once or a boomerang that always returns to you with one dollar?', 'id': 310},
{'question': 'Would you rather have someone secretly give you LSD on a random day and time once every 6 months or have everyone in the world all take LSD at the same time once every 5 years?', 'id': 311},
{'question': 'Would you rather all electrical devices mysteriously stop working (possibly forever) or the governments of the world are only run by people going through puberty?', 'id': 312},
{'question': 'Would you rather give up social media or eat the same dinner for the rest of your life?', 'id': 313},
{'question': 'Would you rather lose all of the money you’ve earned this year or lose all of the memories you’ve gained this year?', 'id': 314},
{'question': 'Would you rather have no taste or be colorblind?', 'id': 315},
{'question': 'Would you rather know the date of your death or the cause of your death?', 'id': 316},
{'question': 'Would you rather flip a coin for a chance to win $20 or immediately win $10?', 'id': 317},
{'question': 'Would you rather always hit a red light for the rest of your life or always get slow internet after the sun goes down?', 'id': 318},
{'question': 'Would you rather have the lights on or off if you knew the room was full of snakes?', 'id': 319},
{'question': 'Would you rather be the person who flips the switch during executions or be the judge who decides who should be executed?', 'id': 320},
{'question': 'Would you rather go blind or deaf?', 'id': 321},
{'question': 'Would you rather be married to someone good-looking who doesn’t think you’re attractive or be married to someone ugly who thinks you’re gorgeous?', 'id': 322},
{'question': 'Would you rather win $25,000 or have your best friend win $100,000?', 'id': 323},
{'question': 'Would you rather work a high-paying job that you hate or your dream job with only enough money for basic necessities?', 'id': 324},
{'question': 'Would you rather wake up in your underwear at work or wake up naked in the woods 20 miles from home?', 'id': 325},
{'question': 'Would you rather find $100 floating in a public toilet or $5 in your pocket?', 'id': 326},
{'question': 'Would you rather be able to read someone’s mind or control their mind?', 'id': 327},
{'question': 'Would you rather look at your mom’s search history or your dad’s search history?', 'id': 328},
{'question': 'Would you rather let your parents access your browsing history or your boss?', 'id': 329},
{'question': 'Would you rather fight a chicken to the death every time you get into a car or fight an orangutan to the death once a year, but you get a sword?', 'id': 330},
{'question': 'Would you rather get a text from a one-night stand that says “i’m pregnant” or “i have an incurable std”?', 'id': 331},
{'question': 'Would you rather forget your favorite books so you can reread them again for the first time or forget your favorite movies so you can rewatch them for the first time?', 'id': 332},
{'question': 'Would you rather always be 20 minutes late for important events or always be 2 hours early to everything else?', 'id': 333},
{'question': 'Would you rather always feel the urge to pee or never know when you have to pee (always wear a diaper)?', 'id': 334},
{'question': 'Would you rather find a dead body or be a witness to a deadly assault?', 'id': 335},
{'question': 'Would you rather only be able to wash your hair twice a year or only be able to check your phone once a day?', 'id': 336},
{'question': 'Would you rather eat a live worm or be locked in a room with a tarantula for an hour (but not know where the tarantula is)?', 'id': 337},
{'question': 'Would you rather be able to change the future or the past, just by imagining it?', 'id': 338},
{'question': 'Would you rather have thought bubbles appear over your head for everyone to see or for everyone you know to have access to your search history?', 'id': 339},
{'question': 'Would you rather be 4 years old your entire life or be 90 years old your entire life?', 'id': 340},
{'question': 'Would you rather save 3 of your closest family members or 1,000 people you don’t know?', 'id': 341},
{'question': 'Would you rather have a lot of mediocre friends or only one really good friend?', 'id': 342},
{'question': 'Would you rather smack a puppy or get smacked by your dad in public?', 'id': 343},
{'question': 'Would you rather turn pink every time someone said “hello” or get really angry every time someone said “bless you”?', 'id': 344},
{'question': 'Would you rather date the hottest person in the world but not be able to have sex with them or date an ugly person that you can have sex with?', 'id': 345},
{'question': 'Would you rather give up your salary for the next five years or give up everything you have in the bank right now?', 'id': 346},
{'question': 'Would you rather lose all your teeth or lose a day of your life every time you kissed someone?', 'id': 347},
{'question': 'Would you rather would you rather have sex with your cousin in secret or not have sex with your cousin but everyone thinks you did?', 'id': 348},
{'question': 'Would you rather wake up in the middle of a good dream every time and not be able to fall back to sleep or never be able to wake yourself up from a nightmare?', 'id': 349},
{'question': 'Would you rather give up cursing forever or give up ice cream for 10 years?', 'id': 350},
{'question': 'Would you rather if you were stranded on an island with no food with you dog and your sibling, would you kill your dog to feed your sibling or let your sibling die of hunger?', 'id': 351},
{'question': 'Would you rather always have tangled hair or always have wet underarms?', 'id': 352},
{'question': 'Would you rather get a pimple the night before important dates or get sick every time after a important date is over?', 'id': 353},
{'question': 'Would you rather lose all of your friends but win the lottery or keep your friends but you don’t get a raise for the rest of your life?', 'id': 354},
{'question': 'Would you rather alk to animals or speak all human languages?', 'id': 355},
{'question': 'Would you rather be reborn into the past or the future?', 'id': 356},
{'question': 'Would you rather be able to run 200 miles an hour or be able to fly 20 miles an hour?', 'id': 357},
{'question': 'Would you rather give up your favorite food or give up sex?', 'id': 358},
{'question': 'Would you rather eat dinner alone for a year or have to take showers at a public gym for a year?', 'id': 359},
{'question': 'Would you rather die before your spouse or after?', 'id': 360},
{'question': 'Would you rather get stranded on antarctica or in the desert?', 'id': 361},
{'question': 'Would you rather give up brushing your teeth or brushing your hair?', 'id': 362},
{'question': 'Would you rather win the lottery or live—in good health—to be 200 years old?', 'id': 363},
{'question': 'Would you rather never age physically or never age mentally?', 'id': 364},
{'question': 'Would you rather be able to play every musical instrument or master every type of sport?', 'id': 365},
{'question': 'Would you rather be a vegetarian or only be able to eat meat?', 'id': 366},
{'question': 'Would you rather have no friends but be rich or have lots of friends but be dirt poor?', 'id': 367},
{'question': 'Would you rather marry the person of your dreams or have the job of your dreams?', 'id': 368},
{'question': 'Would you rather have a pause button in your life or a rewind button?', 'id': 369},
{'question': 'Would you rather have your parents walk in on you while you were doing it or accidentally walk in on them doing it?', 'id': 370},
{'question': 'Would you rather fart out loud during a presentation or snort while laughing on a great first date?', 'id': 371},
{'question': 'Would you rather always be overdressed or always be underdressed?', 'id': 372},
{'question': 'Would you rather drown to death burned to death?', 'id': 373},
{'question': 'Would you rather constantly itch or be in excruciating pain for a whole day once a year?', 'id': 374},
{'question': 'Would you rather always have full battery for your phone or always have a full tank of gas for your car?', 'id': 375},
{'question': 'Would you rather have bad breath or smelly feet?', 'id': 376},
{'question': 'Would you rather fight 1,000 ant-sized bulls or one bull-sized ant?', 'id': 377},
{'question': 'Would you rather have a hamster-sized dog or a dog-sized hamster?', 'id': 378},
{'question': 'Would you rather have spaghetti for hair or sweat mayonnaise?', 'id': 379},
{'question': 'Would you rather live forever with an eyelash in your eye or spinach in your teeth?', 'id': 380},
{'question': "Would you rather adopt a British accent every time you're having a serious conversation or laugh every time someone cries?", 'id': 381},
{'question': 'Would you rather only be able to whisper or only be able to shout?', 'id': 382},
{'question': 'Would you rather give up chocolate for a year or your smartphone for a month?', 'id': 383},
{'question': 'Would you rather get a face tattoo of something of your choosing or a tattoo in a discreet area chosen by someone else?', 'id': 384},
{'question': 'Would you rather talk like Yoda or breathe like Darth Vader?', 'id': 385},
{'question': 'Would you rather sneeze every time you say hi or have the urge to pee every time you ask a question?', 'id': 386},
{'question': 'Would you rather wear jeans one size too small or shoes two sizes too big?', 'id': 387},
{'question': 'Would you rather have a head the size of a tennis ball or the size of a watermelon?', 'id': 388},
{'question': 'Would you rather be in a real-life version of The Walking Dead or Jurassic Park?', 'id': 389},
{'question': 'Would you rather only be able to watch one show for the rest of your life or only be able to watch the first episode of any show for the rest of your life?', 'id': 390},
{'question': 'Would you rather stub your toe or get a paper cut?', 'id': 391},
{'question': 'Would you rather accidentally like an old photo of your ex on Instagram or accidentally send a sext to your mom?', 'id': 392},
{'question': 'Would you rather have your Netflix viewing history made public or your Spotify listening history made public?', 'id': 393},
{'question': 'Would you rather lose the ability to use GPS for the rest of your life or lose the ability to use a credit card?', 'id': 394},
{'question': 'Would you rather only be able to communicate via emojis or only be able to communicate via slang words?', 'id': 395},
{'question': "Would you rather have to hunt for everything you eat or eat only McDonald's for every meal?", 'id': 396},
{'question': 'Would you rather be in a fight club that meets once a month or a book club that meets every day?', 'id': 397},
{'question': "Would you rather always say what you're thinking or never be able to speak again?", 'id': 398},
{'question': 'Would you rather be forced to sing along to every song that you hear or be forced to dance along to every song that you hear?', 'id': 399},
{'question': 'Would you rather live in the Harry Potter universe with no powers or be a Death Eater?', 'id': 400},
{'question': 'Would you rather go without deodorant the day you meet your celebrity crush or run into them when you just rolled out of bed?', 'id': 401},
{'question': 'Would you rather have "Baby Shark" stuck in your head forever or the jingle from your least favorite commercial?', 'id': 402},
{'question': "Would you rather your pet be able to speak to you but not understand what you're saying or your pet understand every word you say but not be able to speak?", 'id': 403},
{'question': 'Would you rather watch your most embarrassing childhood moment on a one-hour loop every month or remember it once every day for the rest of your life?', 'id': 404},
{'question': 'Would you rather sing your favorite song all by yourself in front of an arena full or people or just in front of the original artist alone?', 'id': 405},
{'question': "Would you rather glow bright pink every time you're attracted to someone or glow bright red every time someone annoys you?", 'id': 406},
{'question': 'Would you rather let your boss or your parents see your full internet history?', 'id': 407},
{'question': 'Would you rather wear hideous glasses that are perfect for your eyesight or flattering ones that make your vision a tiny bit blurry?', 'id': 408},
{'question': '''Would you rather own a car with a horn that plays "YMCA" every time you touch it or own a car with your kid's favorite cartoon painted on the side?''', 'id': 409},
{'question': "Would you rather have to wear a bib every time you go out to eat or drink from a sippy cup every time you're at a bar?", 'id': 410},
{'question': 'Would you rather eat the same meal every day for the rest of your life or never get to eat out again?', 'id': 411},
{'question': 'Would you rather have the power of invisibility or be able to fly?', 'id': 412},
{'question': 'Would you rather have to kiss every person you meet or never kiss your partner again?', 'id': 413},
{'question': 'Would you rather have to shower every day in scalding hot water or in freezing cold water?', 'id': 414},
{'question': "Would you rather know when you're going to die or how you're going to die?", 'id': 415},
{'question': 'Would you rather lose the ability to read or the ability to speak?', 'id': 416},
{'question': 'Would you rather never have to wait in line or always have a parking spot?', 'id': 417},
{'question': 'Would you rather never be able to die or have to relive your death over and over for all of eternity?', 'id': 418},
{'question': 'Would you rather sing everything you say or dance every time you walk?', 'id': 419},
{'question': 'Would you rather lose a finger or have a headache every day for the rest of your life?', 'id': 420},
{'question': 'Would you rather always get stuck in traffic or always have a terribly slow internet connection?', 'id': 421},
{'question': 'Would you rather never use the internet again or never fly on an airplane again?', 'id': 422},
{'question': 'Would you rather have all of your Google searches or all of the photos on your phone made public?', 'id': 423},
{'question': 'Would you rather give up brushing your hair or brushing your teeth for the rest of your life?', 'id': 424},
{'question': 'Would you rather pay for sex or be paid to have sex?', 'id': 425},
{'question': "Would you rather be able to control your own emotions or be able to control other people's emotions?", 'id': 426},
{'question': 'Would you rather have eyes that can film everything or ears that can record everything?', 'id': 427},
{'question': 'Would you rather be extremely wealthy but only able to walk everywhere or broke but able to travel anywhere in the world?', 'id': 428},
{'question': 'Would you rather have to wear wet socks every day or only be allowed to wash your hair once a year?', 'id': 429},
{'question': 'Would you rather get lost in the wilderness or in a dangerous city?', 'id': 430},
{'question': 'Would you rather have chapped lips you can never get rid of or dandruff you can never get rid of?', 'id': 431},
{'question': 'Would you rather never be able to go out during the day or never be able to go out at night?', 'id': 432},
{'question': 'Would you rather only be able to eat something that comes out of a can or only eat something that grows in the ground?', 'id': 433},
{'question': 'Would you rather be allergic to sunlight or allergic to your own sweat?', 'id': 434},
{'question': 'Would you rather never be able to get a haircut again or never be able to shave again?', 'id': 435},
{'question': 'Would you rather have your own personal chef or instantly become a gourmet chef yourself?', 'id': 436},
{'question': 'Would you rather get in a fistfight with a stronger person or fall down a flight of stairs?', 'id': 437},
{'question': 'Would you rather always be dressed a little too cold or a little too warm for the weather (no taking off layers!)?', 'id': 438},
{'question': 'Would you rather live in a different fancy hotel every night with unlimited room service credit or live in your dream home but not be able to hire any help?', 'id': 439},
{'question': 'Would you rather be shot into space or explore the deepest depths of the sea?', 'id': 440},
{'question': 'Would you rather be the funniest person in every room or the most intelligent person in every room?', 'id': 441},
{'question': 'Would you rather be trapped on a desert island with someone who never speaks or with someone who never shuts up?', 'id': 442},
{'question': "Would you rather never be able to lie or never be able to tell when someone's lying to you?", 'id': 443},
{'question': 'Would you rather switch places with a spider or a mouse?', 'id': 444},
{'question': 'Would you rather have an assistant to reply to all of your emails or an assistant to do all of your grocery shopping?', 'id': 445},
{'question': 'Would you rather have your S.O. look through all your text/chat/email history or your boss?', 'id': 446},
{'question': 'Would you rather be in a bad relationship for the rest of your life or be single forever?', 'id': 447},
{'question': 'Would you rather get matching piercings or matching tattoos?', 'id': 448},
{'question': 'Would you rather date someone much older than you or much younger than you?', 'id': 449},
{'question': 'Would you rather your partner had really long hair or no hair at all?', 'id': 450},
{'question': "Would you rather be with someone who's always really late or who's always really early?", 'id': 451},
{'question': 'Would you rather have a partner who takes a lot of selfies or one who takes a lot of pictures of you?', 'id': 452},
{'question': 'Would you rather your partner had a job that was life-threatening or one that took up a lot of their time?', 'id': 453},
{'question': 'Would you rather let your partner choose every movie you watch or pick every restaurant you eat at?', 'id': 454},
{'question': "Would you rather wear your S.O.'s underwear or go commando?", 'id': 455},
{'question': 'Would you rather date someone who your family loves and your friends despise or who your friends love and your family despises?', 'id': 456},
{'question': 'Would you rather own five dogs or ten cats?', 'id': 457},
{'question': 'Would you rather marry someone who does not love you or marry someone you do not love?', 'id': 458},
{'question': 'Would you rather have an arranged marriage or spend the rest of your life single?', 'id': 459},
{'question': "Would you rather date someone with their ex's name tattooed on their chest or date someone whose ex lives next door?", 'id': 460},
{'question': 'Would you rather get cheated on and know about it or not get cheated on and always be suspicious?', 'id': 461},
{'question': 'Would you rather exist in a world with only your S.O. or everyone but your S.O.?', 'id': 462},
{'question': 'Would you rather be rich and alone or be poor and find true love?', 'id': 463},
{'question': 'Would you rather let your S.O. look at your text messages or let them control your finances?', 'id': 464},
{'question': 'Would you rather find out your partner hates dogs or find out that they cheated on their ex?', 'id': 465},
{'question': 'On a first date, would you rather have hiccups the entire time or noticeably spill sauce on your shirt?', 'id': 466},
{'question': 'Would you rather wear a Halloween costume to your wedding or wear sweatpants on every date for the next two years?', 'id': 467},
{'question': 'Would you rather get stuck in an elevator with your ex or with your partner and their ex?', 'id': 468},
{'question': 'Would you rather date someone with an overbearing ex or someone with overbearing parents?', 'id': 469},
{'question': 'Would you rather have 10 kids or none at all?', 'id': 470},
{'question': 'Would you rather feel like you know your partner better than anyone or feel like they surprise you every day?', 'id': 471},
{'question': 'Would you rather have the ability to always pick out the perfect gift for your partner or have them always be able to pick out the perfect gift for you?', 'id': 472},
{'question': "Would you rather date someone who doesn't get your favorite movie or someone who can't stand the music you like?", 'id': 473},
{'question': 'Would you rather go on a romantic, lazy beach vacation with your S.O. or a busy tour of a foreign city?', 'id': 474},
{'question': "Would you rather your S.O. read your childhood or everything you've texted about them to your friends?", 'id': 475},
{'question': 'Would you rather be a genius and know everything or be amazing at any activity you tried?', 'id': 476},
{'question': 'Would you rather dine alone or watch a movie by yourself?', 'id': 477},
{'question': 'Would you rather be the richest person in the world or be immortal?', 'id': 478},
{'question': 'Would you rather wear pants 3 sizes too big or shoes 3 sizes too small?', 'id': 479},
{'question': 'Would you rather go into the past and meet your ancestors or go into the future and meet your great-great-grandchildren?', 'id': 480},
{'question': 'Would you rather lose your ability to speak or the ability to hear?', 'id': 481},
{'question': 'Would you rather experience the world beginning or ending?', 'id': 482},
{'question': 'Would you rather have more money or more time?', 'id': 483},
{'question': 'Would you rather only be able to whisper or only be able to shout?', 'id': 484},
{'question': 'Would you rather work more hours a day, but have longer weekends or work fewer hours a day with more workdays?', 'id': 485},
{'question': 'Would you rather live by “Hakuna Matata” or “YOLO”?', 'id': 486},
{'question': 'Would you rather talk like Yoda or breathe like Dark Vader for the rest of your life?', 'id': 487},
{'question': 'Would you rather eat only cheese for 1 year or not be able to eat cheese for 1 year?', 'id': 488},
{'question': 'Would rather have 100 duck-sized elephants or 1 elephant-sized duck?', 'id': 489},
{'question': 'Would you rather wear a clown wig or clown shoes every day?', 'id': 490},
{'question': 'Would you rather have pogo sticks as arms or legs?', 'id': 491},
{'question': 'Would you rather always have a mullet haircut or a ponytail haircut?', 'id': 492},
{'question': 'Would you rather be without elbows or without knees?', 'id': 493},
{'question': 'Would you rather your only mode of transportation be a donkey or a giraffe?', 'id': 494},
{'question': 'Would you rather be a clown who distracts the bull or the cowboy who rides the bull?', 'id': 495},
{'question': 'Would you rather get married to a zombie or give birth to a zombie?', 'id': 496},
{'question': 'Would you rather have baby vomit on you or vomit on a baby?', 'id': 497},
{'question': 'Would you rather get your wisdom teeth pulled or your butt cheeks pierced?', 'id': 498},
{'question': 'Would you rather use boiling water as eye drops or gargle with hot sauce?', 'id': 499},
{'question': 'Would you rather be smacked in the face with a fish or farted on?', 'id': 500},
{'question': 'Would you rather drink water from a vase that has 2 week old flowers, or eat a giant 3 foot spiderweb?', 'id': 501},
{'question': "Would you rather eat a stranger's toenails clippings once a week or have everything smell like garbage?", 'id': 502},
{'question': 'Would you rather pee through your mouth every time or have your best friend pee into your mouth one time?', 'id': 503},
{'question': 'Would you rather be a tissue paper or toilet paper?', 'id': 504},
{'question': 'Would you rather eat a dead pigeon or eat a dead dove?', 'id': 505},
{'question': 'Would you rather lose the ability to lie or believe everything you’re told?', 'id': 506},
{'question': "Would you rather lose all of the money you've earned this year or lose all of the memories you've gained this year?", 'id': 507},
{'question': 'Always hit a red light for the rest of your life or always get slow internet after the sun goes down?', 'id': 508},
{'question': 'Would you rather know how you will die or when you will die?', 'id': 509},
{'question': 'Would you rather have a permanent splinter under your big toenail, or have a permanent bad haircut?', 'id': 510},
{'question': 'Would you rather know the world’s secrets or live ignorantly forever?', 'id': 511},
{'question': 'Would you rather speak to animals or know other people’s thoughts?', 'id': 512},
{'question': 'Would you rather be a cannablist for the rest of your life or starve to death?', 'id': 513},
{'question': 'Would you rather be the person who flips the switch during executions or be the judge who decides who should be executed?', 'id': 514},
{'question': 'Would you rather always have the urge to pee or have to always wear a diaper?', 'id': 515},
{'question': 'Would you rather have a rewind button or a pause button on your life?', 'id': 516},
{'question': 'Would you rather be super strong or super fast?', 'id': 517},
{'question': 'Would you rather go on a rollercoaster or go sky diving?', 'id': 518},
{'question': 'Would you rather be always cold or always hot?', 'id': 519},
{'question': 'Would you rather be really tall or really short?', 'id': 520},
{'question': 'Would you rather be attacked by an insane murderer or be given a million dollars every day for the rest of your life?', 'id': 521},
{'question': 'Would you rather get a paper cut every time you read a book or get a free pair of Jordans?', 'id': 522},
{'question': 'Would you rather drink black tea or have coffee everyday?', 'id': 523},
{'question': 'Would you rather have your own robot or a jetpack?', 'id': 524},
{'question': 'Would you rather be in a ballet class or a salsa class?', 'id': 525},
{'question': 'Would you rather be reincarnated as a sea creature or an airborne creature?', 'id': 526},
{'question': 'Would you rather the aliens that make first contact be robotic or organic?', 'id': 527},
{'question': 'Would you rather have a pet skunk that sprayed you once a month or a pet porcupine that quilled you once a month?', 'id': 528},
{'question': 'Would you rather have an odd shaped nose or odd shape ears?', 'id': 529},
{'question': 'Would you rather have a daughter have Hulk powers or a son with Beyonce’s talent?', 'id': 530},
{'question': 'Would you rather still be bathed for by your mother or by your grandmother?', 'id': 531},
{'question': 'Would you rather have 10,000 spoons when all you need is a knife or always have a knife but never be able to use spoons?', 'id': 532},
{'question': 'Would you rather your mother or your father pick your future spouse?', 'id': 533},
{'question': 'Would you rather be get trapped inside a video game or have that video game come to life in the real world?', 'id': 534},
{'question': 'Wake up in your underwear at work or wake up naked in the woods 20 miles from home?', 'id': 535},
    ]